# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttachmentType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=250, null=True)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.CarMark')),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceContractStatus',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
