# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('handbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecontractstatus',
            name='availiable_action_types',
            field=models.ManyToManyField(related_name='availiable_insurance_statuses', to='contract.ActionType'),
        ),
    ]
