# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-17 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbooks', '0002_insurancecontractstatus_availiable_action_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecontractstatus',
            name='availiable_action_types',
            field=models.ManyToManyField(blank=True, related_name='availiable_insurance_statuses', to='contract.ActionType'),
        ),
    ]
