# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:37
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=255)),
                ('kladr', models.CharField(max_length=255)),
                ('address_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.AddressType')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('file', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=255)),
                ('attachment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.AttachmentType')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('engine_power', models.PositiveIntegerField()),
                ('engine_power_kilowatt', models.FloatField()),
                ('manufacturing_date', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('number_plate', models.CharField(max_length=9)),
                ('vin_number', models.CharField(max_length=17)),
                ('car_mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.CarMark')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.CarModel')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('data', models.CharField(max_length=255)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.ContactType')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('number', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('issue_point', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('credential_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.CredentialType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredObjectParameter',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('param_type', models.CharField(max_length=255)),
                ('is_required', models.NullBooleanField(default=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_many', models.NullBooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuredObjectType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.InsuranceType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('title', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birth_date', models.DateField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NaturalPersonGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('natural_persons', models.ManyToManyField(to='client.NaturalPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('legal_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.LegalPerson')),
                ('natural_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.NaturalPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='insuredobjectparameter',
            name='insured_object_types',
            field=models.ManyToManyField(to='client.InsuredObjectType'),
        ),
        migrations.AddField(
            model_name='insuredobject',
            name='insurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Person'),
        ),
        migrations.AddField(
            model_name='insuredobject',
            name='insured_object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.InsuredObjectType'),
        ),
        migrations.AlterUniqueTogether(
            name='insuredobjecttype',
            unique_together=set([('department', 'insurance_type', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='insuredobjectparameter',
            unique_together=set([('code',)]),
        ),
    ]
