# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 16:38
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbooks', '0001_initial'),
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ActionParameter',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('param_type', models.CharField(max_length=255)),
                ('is_required', models.NullBooleanField(default=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_many', models.NullBooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('fail_contract_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fail_action_types', to='handbooks.InsuranceContractStatus')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.InsuranceType')),
                ('successfull_contract_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successfull_action_types', to='handbooks.InsuranceContractStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationParameter',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('param_type', models.CharField(max_length=255)),
                ('is_required', models.NullBooleanField(default=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_many', models.NullBooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalculationType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.InsuranceType')),
                ('payment_types', models.ManyToManyField(related_name='calculation_types', to='handbooks.PaymentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('insurance_contract_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='handbooks.InsuranceContractStatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='contract.Calculation')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultParameter',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('param_type', models.CharField(max_length=255)),
                ('is_required', models.NullBooleanField(default=True)),
                ('is_active', models.NullBooleanField(default=True)),
                ('is_many', models.NullBooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultType',
            fields=[
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbooks.InsuranceType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='resultparameter',
            name='result_types',
            field=models.ManyToManyField(related_name='result_parameters', to='contract.ResultType'),
        ),
        migrations.AddField(
            model_name='result',
            name='result_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='contract.ResultType'),
        ),
        migrations.AddField(
            model_name='insurancecontract',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_contracts', to='contract.Result'),
        ),
        migrations.AddField(
            model_name='calculationparameter',
            name='calculation_types',
            field=models.ManyToManyField(related_name='calculation_parameters', to='contract.CalculationType'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='calculation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='contract.CalculationType'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='actionparameter',
            name='action_types',
            field=models.ManyToManyField(related_name='action_parameters', to='contract.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contract.ActionType'),
        ),
        migrations.AddField(
            model_name='action',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='action',
            name='insurance_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contract.InsuranceContract'),
        ),
        migrations.AlterUniqueTogether(
            name='resulttype',
            unique_together=set([('department', 'insurance_type', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='resultparameter',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='calculationtype',
            unique_together=set([('department', 'insurance_type', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='calculationparameter',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='actiontype',
            unique_together=set([('department', 'insurance_type', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='actionparameter',
            unique_together=set([('code',)]),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('action_type', 'insurance_contract')]),
        ),
    ]
